### ISSUE TITLE
Can't seem to get it to work on Mars.

### ISSUE THREAD

**Issue by LeoUfimtsev** [mmornati/epomodoro#4]
Hello, 

I've tried to install this on Mars (Linux). But when installing it from marketclient it just says that it can't install this package. 

If this is easily reproducible, it would be nice for the package to be updated for Mars use.

**Comment by vincenzocaselli** [comment]
Hello Leo,
maybe the marketplace is not updated.
I tried the official update site of the project
http://repo.mornati.net/eclipse
on Mars, and it went all right.
Can you try this too?
Vincenzo

**Comment by LeoUfimtsev** [comment]
That worked. Thank you for swift reply.
